-- 코드를 입력하세요

SELECT CAR.CAR_ID, CAR.CAR_TYPE, FLOOR(CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100) FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE
AND PLAN.DURATION_TYPE = "30일 이상"
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
ON CAR.CAR_ID = HIS.CAR_ID
AND HIS.START_DATE <= "2022-11-30"
AND HIS.END_DATE >= "2022-11-01"
WHERE CAR.CAR_TYPE IN ("세단", "SUV")
AND HIS.CAR_ID IS NULL
AND FLOOR(CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC
